In [1]:
%matplotlib inline

In [2]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import os

In [12]:
housing_dirty_1 = pd.read_csv('../data/housing_1_dirty.csv')

In [13]:
housing_dirty_2 = pd.read_excel('../data/housing_2_dirty.xlsx')

In [14]:
housing_dirty_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 4 columns):
id                 20640 non-null int64
longitude          20639 non-null float64
latitude           20640 non-null float64
ocean_proximity    20636 non-null object
dtypes: float64(2), int64(1), object(1)
memory usage: 645.1+ KB

In [15]:
housing_dirty_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20567 entries, 0 to 20566
Data columns (total 8 columns):
id                    20567 non-null int64
housing_median_age    20566 non-null float64
total_rooms           20564 non-null float64
total_bedrooms        20359 non-null float64
population            20564 non-null float64
households            20566 non-null float64
median_income         20567 non-null float64
median_house_value    20565 non-null float64
dtypes: float64(7), int64(1)
memory usage: 1.3 MB

In [16]:
data = pd.merge(housing_dirty_1, housing_dirty_2, on="id")
data

,id,longitude,latitude,ocean_proximity,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,1,-122.23,37.88,NEAR BAY,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0
1,2,-122.22,37.86,NEAR BAY,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0
2,3,-122.24,37.85,NEAR BAY,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0
3,4,-122.25,37.85,NEAR BAY,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0
4,5,-122.25,37.85,NEAR BAY,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0
5,6,-122.25,37.85,NEAR BAY,52.0,919.0,213.0,413.0,193.0,4.0368,269700.0
6,7,122.25,37.84,NEAR BAY,52.0,2535.0,489.0,1094.0,514.0,3.6591,299200.0
7,8,-122.25,37.84,NEAR BAY,52.0,3104.0,687.0,1157.0,647.0,3.1200,241400.0
8,9,-122.26,37.84,NEAR BAY,42.0,2555.0,665.0,1206.0,595.0,2.0804,226700.0
9,10,-122.25,37.84,NEAR BAY,52.0,3549.0,707.0,1551.0,714.0,3.6912,261100.0
10,11,-122.26,37.85,NEAR BAY,52.0,2202.0,434.0,910.0,402.0,3.2031,281500.0
11,12,-122.26,37.85,nNEAR OCEAN,52.0,3503.0,752.0,1504.0,734.0,3.2705,241800.0
12,13,-122.26,37.85,nNEAR OCEAN,52.0,2491.0,474.0,1098.0,468.0,3.0750,213500.0
13,14,-122.26,37.84,nNEAR OCEAN,52.0,696.0,191.0,345.0,174.0,2.6736,191300.0
14,15,-122.26,37.85,NEAR BAY,52.0,2643.0,626.0,1212.0,620.0,1.9167,159200.0
15,16,-122.26,37.85,NEAR BAY,50.0,1120.0,283.0,697.0,264.0,2.1250,140000.0
16,17,-122.27,37.85,NEAR BAY,52.0,1966.0,347.0,793.0,331.0,2.7750,152500.0
17,18,-122.27,37.85,NEAR BAY,52.0,1228.0,293.0,648.0,303.0,2.1202,155500.0
18,19,-122.26,37.84,NEAR BAY,50.0,2239.0,455.0,990.0,419.0,1.9911,158700.0
19,20,-122.27,37.84,NEAR BAY,52.0,1503.0,298.0,690.0,275.0,2.6033,162900.0
20,21,-122.27,37.85,NEAR BAY,40.0,751.0,184.0,409.0,166.0,1.3578,147500.0
21,22,-122.27,37.85,NEAR BAY,42.0,1639.0,367.0,929.0,366.0,1.7135,159800.0
22,23,-122.27,37.84,NEAR BAY,52.0,2436.0,541.0,1015.0,478.0,1.7250,113900.0
23,24,-122.27,37.84,NEAR BAY,52.0,1688.0,337.0,853.0,325.0,2.1806,99700.0
24,25,-122.27,37.84,NEAR BAY,52.0,2224.0,437.0,1006.0,422.0,2.6000,132600.0
25,26,-122.28,37.85,NEAR BAY,41.0,535.0,123.0,317.0,119.0,2.4038,107500.0
26,27,-122.28,37.85,NEAR BAY,49.0,1130.0,244.0,607.0,239.0,2.4597,93800.0
27,28,-122.28,37.85,NEAR BAY,52.0,1898.0,421.0,1102.0,397.0,1.8080,105500.0
28,29,-122.28,37.84,NEAR BAY,50.0,2082.0,492.0,1131.0,473.0,1.6424,108900.0
29,30,-122.28,37.84,NEAR BAY,52.0,729.0,160.0,395.0,155.0,1.6875,132000.0
...,...,...,...,...,...,...,...,...,...,...,...
20537,20538,-121.73,38.54,INLAND,18.0,974.0,317.0,521.0,317.0,1.0633,137500.0
20538,20539,-121.73,38.56,INLAND,30.0,3306.0,629.0,1623.0,648.0,2.8614,145200.0
20539,20540,-121.71,38.56,INLAND,20.0,8627.0,1516.0,4071.0,1466.0,4.2198,164100.0
20540,20541,-121.72,38.54,INLAND,16.0,2790.0,624.0,1386.0,636.0,3.1908,194300.0
20541,20542,-121.70,38.54,INLAND,13.0,6819.0,1158.0,2828.0,1115.0,4.6225,226500.0
20542,20543,-121.75,38.55,INLAND,33.0,2479.0,382.0,979.0,377.0,4.7308,236200.0
20543,20544,-121.74,38.55,INLAND,33.0,6861.0,1820.0,3717.0,1767.0,1.7311,182600.0
20544,20545,-121.76,38.55,INLAND,23.0,8800.0,1857.0,6330.0,1832.0,2.0650,219400.0
20545,20546,-121.75,38.55,INLAND,26.0,4802.0,950.0,2199.0,939.0,3.7452,227700.0
20546,20547,-121.77,38.69,INLAND,47.0,1697.0,318.0,775.0,276.0,3.4559,123100.0
20547,20548,-121.77,38.68,INLAND,43.0,2559.0,598.0,1820.0,591.0,2.1927,107900.0
20548,20549,-121.76,38.68,INLAND,38.0,674.0,178.0,701.0,189.0,1.3942,69400.0
20549,20550,-121.80,38.69,INLAND,8.0,3544.0,691.0,2118.0,678.0,3.7477,122200.0
20550,20551,-121.79,38.69,INLAND,23.0,1755.0,321.0,1061.0,313.0,2.8864,103100.0
20551,20552,-121.78,38.69,INLAND,31.0,2547.0,535.0,1579.0,509.0,2.6774,95800.0
20552,20553,-121.80,38.68,INLAND,11.0,3851.0,892.0,1847.0,747.0,3.4331,120600.0
20553,20554,-121.79,38.68,INLAND,24.0,3794.0,848.0,2225.0,864.0,2.8068,95300.0
20554,20555,-121.78,38.68,INLAND,39.0,2806.0,662.0,1659.0,638.0,1.9787,97800.0
20555,20556,-121.80,38.67,INLAND,11.0,3251.0,623.0,1700.0,615.0,3.1875,172000.0
20556,20557,-121.79,38.67,INLAND,17.0,2875.0,810.0,1876.0,749.0,1.9510,152500.0
20557,20558,-121.78,38.68,INLAND,43.0,3766.0,847.0,1855.0,817.0,2.3468,119400.0
20558,20559,-121.80,38.67,INLAND,10.0,2086.0,380.0,1073.0,378.0,4.5526,154400.0
20559,20560,-121.79,38.67,INLAND,30.0,2602.0,401.0,981.0,405.0,4.7222,167200.0
20560,20561,-121.78,38.67,INLAND,38.0,2948.0,478.0,1123.0,460.0,4.0556,146900.0
20561,20562,-121.77,38.67,INLAND,42.0,2670.0,518.0,1548.0,534.0,2.2794,108900.0
20562,20563,-121.77,38.67,INLAND,45.0,2438.0,462.0,1415.0,510.0,2.8351,107200.0
20563,20564,-121.75,38.67,INLAND,9.0,12139.0,2640.0,6837.0,2358.0,3.1250,132500.0
20564,20565,-121.71,38.72,INLAND,32.0,710.0,155.0,550.0,154.0,2.8882,151400.0
20565,20566,-121.70,38.65,INLAND,22.0,1360.0,282.0,808.0,229.0,2.4167,225000.0
20566,20567,-121.84,38.65,INLAND,29.0,3167.0,548.0,1554.0,534.0,4.3487,200700.0

In [17]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 20567 entries, 0 to 20566
Data columns (total 11 columns):
id                    20567 non-null int64
longitude             20566 non-null float64
latitude              20567 non-null float64
ocean_proximity       20563 non-null object
housing_median_age    20566 non-null float64
total_rooms           20564 non-null float64
total_bedrooms        20359 non-null float64
population            20564 non-null float64
households            20566 non-null float64
median_income         20567 non-null float64
median_house_value    20565 non-null float64
dtypes: float64(9), int64(1), object(1)
memory usage: 1.9+ MB

In [18]:
data.isnull().sum()

id                      0
longitude               1
latitude                0
ocean_proximity         4
housing_median_age      1
total_rooms             3
total_bedrooms        208
population              3
households              1
median_income           0
median_house_value      2
dtype: int64

In [23]:
data[data["total_bedrooms"].isna()].head()

,id,longitude,latitude,ocean_proximity,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
290,291,-122.16,37.77,NEAR BAY,47.0,1256.0,NaN,570.0,218.0,4.3750,161900.0
341,342,-122.17,37.75,NEAR BAY,38.0,992.0,NaN,732.0,259.0,1.6196,85100.0
538,539,-122.28,37.78,NEAR BAY,29.0,5154.0,NaN,3741.0,1273.0,2.5762,173400.0
563,564,-122.24,37.75,NEAR BAY,45.0,891.0,NaN,384.0,146.0,4.9489,247100.0
696,697,-122.10,37.69,NEAR BAY,41.0,746.0,NaN,387.0,161.0,3.9063,178400.0

In [24]:
data.head()

,id,longitude,latitude,ocean_proximity,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,1,-122.23,37.88,NEAR BAY,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0
1,2,-122.22,37.86,NEAR BAY,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0
2,3,-122.24,37.85,NEAR BAY,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0
3,4,-122.25,37.85,NEAR BAY,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0
4,5,-122.25,37.85,NEAR BAY,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0

In [26]:
data["total_bedrooms"].describe()

count    20359.000000
mean       538.399872
std        421.724100
min          1.000000
25%        296.000000
50%        435.000000
75%        647.000000
max       6445.000000
Name: total_bedrooms, dtype: float64

In [29]:
data["ocean_proximity"].value_counts(dropna=False)

<1H OCEAN      9131
INLAND         6478
NEAR OCEAN     2655
NEAR BAY       2287
nNEAR OCEAN       7
ISLAND            5
NaN               4
Name: ocean_proximity, dtype: int64

In [30]:
from sklearn.ensemble import RandomForestRegressor

In [32]:
regr = RandomForestRegressor(max_depth=2, random_state=0, n_estimators=100)

In [33]:
regr.fit(data.drop(columns="median_house_value"), data["median_house_value"])

ValueError: could not convert string to float: 'NEAR BAY'